blockSzie: 16777216  # 16 * 1024 * 1024
duplicateNumber: 1

server:
  port: 9092

logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
    net.wenz.service.fs: DEBUG

spring:
  devtools:
    livereload:
      enabled: true #是否支持livereload
      port: 35730
    restart:
      enabled: true #热部署生效
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microsfs?useUnicode=true&characterEncoding=utf8
    username: root
    password: 'Ailab@315'
    maxActive: 500

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: net.wenz.service.fs.model.entity  # 注意：对应实体类的路径
  type-handlers-package: net.wenz.service.fs.model.dao.typehandler
